const CONSTANT_MESSAGES={
NOT_FOUND :"USER ALREADY FOUND",
APPENDED:"DATA APPENDED",
FILE_NOT_FOUND:"FILE NOT FOUND",
DELETE_MESSAGE:"NO DATA TO DELETE",
ALL_DATA_DELETE:"ALL DATA DELETED",
BUDDY_NOT_FOUND:"BUDDY NOT FOUND",
DELETE_USER:"DELETED USER",
UPDATED_USER:"UPDATED USER",
}
module.exports={CONSTANT_MESSAGES}